"""
Encoding round-trip tests for 8-Puzzle and Blocks World datasets.

WHY THIS EXISTS
---------------
Every bug we've found in this experiment has been an encoding issue:
  - 8-puzzle cache stores PRE-move state instead of POST-move state
  - Blocks World encoder reuses POS_0 as padding for empty towers (ambiguous)
  - 8-puzzle action tokens use IDs 10-13 in data, but the trainer constants
    used to claim 9-12 (since fixed, but caused confusion for hours)
  - Cache files on disk were sometimes generated by older scripts that no
    longer exist in the repo, with conventions different from the current
    encoder code
This suite catches these systematically instead of one-by-one through
downstream failures.

LAYERS OF TESTING
-----------------
Layer 1: Strict round-trip
    raw_problem -> encode -> decode -> raw_problem'
    Check raw_problem == raw_problem' (where possible)

Layer 2: Lossy round-trip (Blocks World)
    Acknowledge that Blocks World state encoding loses information.
    Verify only what should be preserved: top-blocks-by-position view.
    Document what's lost.

Layer 3: Generator-to-encoder consistency on FRESHLY GENERATED problems
    For a newly generated problem, encode it, decode it, and verify:
      - The decoded action sequence equals the generated action sequence
      - Applying the decoded actions to the decoded start state reaches the
        decoded goal state (the decoded plan is valid)
      - Encoded state-blocks correspond to actual intermediate states under
        the post-move convention

Layer 4: Cache verification (CRITICAL)
    For each CACHED problem on disk, decode and check internal consistency.
    This catches caches generated by old scripts that no longer match the
    current encoder. This is the test we wish we'd had from the start.

USAGE
-----
    python3 test_encoding_roundtrip.py
    python3 test_encoding_roundtrip.py --domain eight_puzzle
    python3 test_encoding_roundtrip.py --domain blocks_world
    python3 test_encoding_roundtrip.py --skip-cache    # if no cache files exist
    python3 test_encoding_roundtrip.py --num-fresh 5   # check N freshly generated
"""

import argparse
import json
import sys
from copy import deepcopy
from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple

import numpy as np


# ============================================================================
# 8-PUZZLE encoding/decoding
# ============================================================================

EP_MOVE_TO_TOKEN = {'up': 10, 'down': 11, 'left': 12, 'right': 13}
EP_TOKEN_TO_MOVE = {v: k for k, v in EP_MOVE_TO_TOKEN.items()}
EP_SEP = 14
EP_PAD = 15
EP_DUMMY = 13  # 'right' used as the leading dummy token


def ep_apply_move(state: np.ndarray, move: str) -> Optional[np.ndarray]:
    """Apply a single move to a 3x3 state. Returns new state or None if invalid."""
    s = state.copy()
    pos = np.argwhere(s == 0)
    if len(pos) == 0:
        return None
    r, c = pos[0]
    if move == 'up' and r > 0:
        s[r, c], s[r-1, c] = s[r-1, c], s[r, c]
    elif move == 'down' and r < 2:
        s[r, c], s[r+1, c] = s[r+1, c], s[r, c]
    elif move == 'left' and c > 0:
        s[r, c], s[r, c-1] = s[r, c-1], s[r, c]
    elif move == 'right' and c < 2:
        s[r, c], s[r, c+1] = s[r, c+1], s[r, c]
    else:
        return None
    return s


def ep_decode_problem(seq: List[int], use_world_model: bool) -> Dict[str, Any]:
    """Decode an 8-puzzle token sequence into a structured problem dict.

    Layout (use_world_model=True):
      [dummy=13, start(9), PAD=15, goal(9),
       for each move m_k:  m_k, state_k(9),
       SEP=14]
    Layout (use_world_model=False):
      [dummy=13, start(9), PAD=15, goal(9),
       move_1, move_2, ..., move_N,
       SEP=14]

    Returns dict with: start_state (3x3 array), goal_state (3x3 array),
    solution_moves (list of strings), solution_states (list of 3x3 arrays,
    one per emitted state block in the sequence), num_moves (int).

    Does NOT verify validity -- that's a separate test.
    """
    if len(seq) < 21:
        raise ValueError(f"sequence too short: len={len(seq)}")
    if seq[0] != EP_DUMMY:
        raise ValueError(f"position 0 is {seq[0]}, expected dummy={EP_DUMMY}")
    if seq[10] != EP_PAD:
        raise ValueError(f"position 10 is {seq[10]}, expected PAD={EP_PAD}")
    if seq[-1] != EP_SEP:
        raise ValueError(f"last token is {seq[-1]}, expected SEP={EP_SEP}")

    start = np.array(seq[1:10]).reshape(3, 3)
    goal = np.array(seq[11:20]).reshape(3, 3)

    moves: List[str] = []
    states: List[np.ndarray] = []
    pos = 20
    while pos < len(seq) - 1:  # leave room for SEP
        tok = seq[pos]
        if tok not in EP_TOKEN_TO_MOVE:
            raise ValueError(
                f"position {pos}: token {tok} is not a move token "
                f"(expected one of {sorted(EP_TOKEN_TO_MOVE)})"
            )
        moves.append(EP_TOKEN_TO_MOVE[tok])
        pos += 1
        if use_world_model:
            if pos + 9 > len(seq) - 1:
                raise ValueError(
                    f"position {pos}: WM expected 9 state tokens before SEP, "
                    f"but only {len(seq) - 1 - pos} remain"
                )
            state = np.array(seq[pos:pos+9]).reshape(3, 3)
            states.append(state)
            pos += 9

    return {
        'start_state': start,
        'goal_state': goal,
        'solution_moves': moves,
        'solution_states': states,  # may be empty for baseline
        'num_moves': len(moves),
    }


def ep_encode_problem(problem: Dict[str, Any], use_world_model: bool) -> List[int]:
    """Encode an 8-puzzle problem the way the current code SHOULD encode it.

    Uses post-move-state convention (which is what we want, and what we'll
    compare cached data against). This is independent of the dataset class.
    """
    seq: List[int] = [EP_DUMMY]
    seq.extend(problem['start_state'].flatten().tolist())
    seq.append(EP_PAD)
    seq.extend(problem['goal_state'].flatten().tolist())

    if use_world_model:
        cur = problem['start_state'].copy()
        for mv in problem['solution_moves']:
            seq.append(EP_MOVE_TO_TOKEN[mv])
            cur = ep_apply_move(cur, mv)
            if cur is None:
                raise ValueError(f"invalid move '{mv}' during encoding")
            seq.extend(cur.flatten().tolist())
    else:
        for mv in problem['solution_moves']:
            seq.append(EP_MOVE_TO_TOKEN[mv])

    seq.append(EP_SEP)
    return seq


# ============================================================================
# BLOCKS WORLD encoding/decoding
# ============================================================================

BW_VOCAB = {
    'START': 0, 'END': 1,
    'A': 2, 'B': 3, 'C': 4, 'D': 5,
    'POS_0': 6, 'POS_1': 7, 'POS_2': 8, 'POS_3': 9,
    'PAD': 10,
}
BW_INV = {v: k for k, v in BW_VOCAB.items()}
BW_BLOCKS = ['A', 'B', 'C', 'D']
BW_NUM_POSITIONS = 4
BW_START = 0
BW_END = 1
BW_STATE_LEN = 8       # uniform: 4 blocks + 4 POS_k separators always present
BW_ACTION_LEN = 2      # [block, POS_k]
BW_CONTEXT_END = 1 + BW_STATE_LEN + BW_STATE_LEN   # 17: START + start_state(8) + goal_state(8)
BW_POS_TOKENS = {BW_VOCAB[f'POS_{k}']: k for k in range(BW_NUM_POSITIONS)}
BW_BLOCK_TOKENS = {BW_VOCAB[b] for b in BW_BLOCKS}


def bw_apply_action(state: List[List[str]], action: List) -> Optional[List[List[str]]]:
    """Apply [block, dest_pos] to state. Returns new state or None if invalid."""
    block, dest_pos = action
    source_pos = None
    for pos_idx, tower in enumerate(state):
        if tower and tower[-1] == block:
            source_pos = pos_idx
            break
    if source_pos is None:
        return None
    new_state = [t[:] for t in state]
    new_state[source_pos].pop()
    new_state[dest_pos].append(block)
    return new_state


def bw_encode_state(state: List[List[str]]) -> List[int]:
    """Uniform 8-token state encoding: top-to-bottom within each tower,
    POS_k separator always emitted (even for empty positions).

    state [['A','B','C'], [], ['D'], []]
        -> [C, B, A, POS_0, POS_1, D, POS_2, POS_3]
    """
    tokens = []
    for pos_idx, tower in enumerate(state):
        for block in reversed(tower):  # top-to-bottom
            tokens.append(BW_VOCAB[block])
        tokens.append(BW_VOCAB[f'POS_{pos_idx}'])
    assert len(tokens) == BW_STATE_LEN, (
        f"state encoding has {len(tokens)} tokens, expected {BW_STATE_LEN}. "
        f"State: {state}"
    )
    return tokens


def bw_decode_state(tokens: List[int]) -> List[List[str]]:
    """Inverse of bw_encode_state. Returns a state in bottom-to-top raw format."""
    if len(tokens) != BW_STATE_LEN:
        raise ValueError(
            f"bw_decode_state: expected {BW_STATE_LEN} tokens, got {len(tokens)}"
        )
    state: List[List[str]] = [[] for _ in range(BW_NUM_POSITIONS)]
    buf: List[str] = []
    for tok in tokens:
        if tok in BW_BLOCK_TOKENS:
            buf.append(BW_INV[tok])
        elif tok in BW_POS_TOKENS:
            state[BW_POS_TOKENS[tok]] = list(reversed(buf))   # top-to-bottom -> bottom-to-top
            buf = []
        else:
            raise ValueError(
                f"bw_decode_state: unexpected token {tok} ({BW_INV.get(tok, '?')})"
            )
    if buf:
        raise ValueError(
            f"bw_decode_state: trailing tokens with no closing POS_k: {buf}"
        )
    return state


def bw_decode_problem(seq: List[int], use_world_model: bool) -> Dict[str, Any]:
    """Decode a Blocks World token sequence into a structured problem dict.

    Uniform layout (use_world_model=True):
      [START=0, start_state(8), goal_state(8),
       for each move m_k: m_k(2 tokens), state_k(8),
       END=1]
    Layout (use_world_model=False):
      [START=0, start_state(8), goal_state(8),
       move_1(2), move_2(2), ..., move_N(2),
       END=1]

    Returns dict with:
      start_state, goal_state             (full semantic states, lossless)
      solution_moves                       (list of [block_str, pos_int])
      solution_states                      (list of full semantic states, one per emitted state block)
      num_moves
    """
    if len(seq) < BW_CONTEXT_END + 1:
        raise ValueError(f"sequence too short: len={len(seq)}")
    if seq[0] != BW_START:
        raise ValueError(f"position 0 is {seq[0]}, expected START={BW_START}")
    if seq[-1] != BW_END:
        raise ValueError(f"last token is {seq[-1]}, expected END={BW_END}")

    start_state = bw_decode_state(seq[1:1 + BW_STATE_LEN])
    goal_state = bw_decode_state(seq[1 + BW_STATE_LEN:BW_CONTEXT_END])

    moves: List[List] = []
    states: List[List[List[str]]] = []
    pos = BW_CONTEXT_END
    while pos < len(seq) - 1:  # leave room for END
        # Action block (2 tokens)
        if pos + BW_ACTION_LEN > len(seq) - 1 and seq[pos] == BW_END:
            break
        if pos + BW_ACTION_LEN > len(seq):
            raise ValueError(f"position {pos}: ran out of tokens reading action")
        block_tok, pos_tok = seq[pos], seq[pos + 1]
        if block_tok not in BW_BLOCK_TOKENS:
            raise ValueError(
                f"position {pos}: expected block token, got {block_tok} ({BW_INV.get(block_tok)})"
            )
        if pos_tok not in BW_POS_TOKENS:
            raise ValueError(
                f"position {pos+1}: expected POS_ token, got {pos_tok} ({BW_INV.get(pos_tok)})"
            )
        moves.append([BW_INV[block_tok], BW_POS_TOKENS[pos_tok]])
        pos += BW_ACTION_LEN

        if not use_world_model:
            continue

        # State block (8 tokens) -- always present after each action in WM
        if pos < len(seq) - 1 and seq[pos] != BW_END:
            if pos + BW_STATE_LEN > len(seq):
                raise ValueError(
                    f"position {pos}: expected {BW_STATE_LEN}-token state block "
                    f"but only {len(seq) - pos} tokens remain"
                )
            states.append(bw_decode_state(seq[pos:pos + BW_STATE_LEN]))
            pos += BW_STATE_LEN

    return {
        'start_state': start_state,
        'goal_state': goal_state,
        'solution_moves': moves,
        'solution_states': states,   # post-move states, one per move (in WM mode)
        'num_moves': len(moves),
    }


def bw_encode_problem(problem: Dict[str, Any], use_world_model: bool) -> List[int]:
    """Encode a Blocks World problem with the uniform lossless encoding.

    Pairs move i with the POST-move state, derived by walking forward from
    start with apply_action. We do NOT rely on problem['solution_states'] here
    -- this is the reference encoder, intentionally independent of however the
    dataset class structures things.
    """
    seq: List[int] = [BW_START]
    seq.extend(bw_encode_state(problem['start_state']))
    seq.extend(bw_encode_state(problem['goal_state']))

    if use_world_model:
        cur = [t[:] for t in problem['start_state']]
        for move in problem['solution_moves']:
            seq.append(BW_VOCAB[move[0]])
            seq.append(BW_VOCAB[f"POS_{move[1]}"])
            cur = bw_apply_action(cur, move)
            if cur is None:
                raise ValueError(f"invalid move {move} while encoding")
            seq.extend(bw_encode_state(cur))
    else:
        for move in problem['solution_moves']:
            seq.append(BW_VOCAB[move[0]])
            seq.append(BW_VOCAB[f"POS_{move[1]}"])

    seq.append(BW_END)
    return seq


# ============================================================================
# Result helper
# ============================================================================

class TestResult:
    def __init__(self, name: str):
        self.name = name
        self.passed = 0
        self.failed = 0
        self.failures: List[str] = []

    def assert_(self, condition: bool, msg: str):
        if condition:
            self.passed += 1
        else:
            self.failed += 1
            self.failures.append(msg)

    def summary(self) -> str:
        status = "✓" if self.failed == 0 else "✗"
        return f"  {status} {self.name}: {self.passed} passed, {self.failed} failed"


# ============================================================================
# Tests
# ============================================================================

def test_ep_layer1_strict_roundtrip(num_problems: int = 3) -> TestResult:
    """Layer 1: Strict round-trip for 8-puzzle."""
    r = TestResult("8-puzzle Layer 1: strict round-trip (fresh problems)")
    try:
        from data.eight_puzzle import EightPuzzleDataset
    except Exception as e:
        r.assert_(False, f"could not import EightPuzzleDataset: {e}")
        return r

    for seed in range(num_problems):
        for use_wm in [False, True]:
            ds = EightPuzzleDataset(difficulty_range=(5, 10), num_samples=1,
                                     use_world_model=use_wm, seed=seed)
            problem = ds.generate_problem(difficulty=5 + seed)

            # Encode using OUR encoder (independent of the dataset class)
            seq = ep_encode_problem(problem, use_world_model=use_wm)
            # Decode it
            decoded = ep_decode_problem(seq, use_world_model=use_wm)

            r.assert_(
                np.array_equal(decoded['start_state'], problem['start_state']),
                f"seed={seed} wm={use_wm}: start_state mismatch"
            )
            r.assert_(
                np.array_equal(decoded['goal_state'], problem['goal_state']),
                f"seed={seed} wm={use_wm}: goal_state mismatch"
            )
            r.assert_(
                decoded['solution_moves'] == problem['solution_moves'],
                f"seed={seed} wm={use_wm}: solution_moves mismatch: "
                f"{decoded['solution_moves']} vs {problem['solution_moves']}"
            )
            r.assert_(
                decoded['num_moves'] == problem['num_moves'],
                f"seed={seed} wm={use_wm}: num_moves {decoded['num_moves']} vs {problem['num_moves']}"
            )
            # WM-only: state blocks must match the post-move trajectory
            if use_wm:
                r.assert_(
                    len(decoded['solution_states']) == problem['num_moves'],
                    f"seed={seed}: expected {problem['num_moves']} state blocks, "
                    f"got {len(decoded['solution_states'])}"
                )
                cur = problem['start_state'].copy()
                for k, mv in enumerate(problem['solution_moves']):
                    cur = ep_apply_move(cur, mv)
                    if k < len(decoded['solution_states']):
                        r.assert_(
                            np.array_equal(decoded['solution_states'][k], cur),
                            f"seed={seed}: state block {k} doesn't match post-move state "
                            f"(decoded={decoded['solution_states'][k].flatten().tolist()}, "
                            f"expected={cur.flatten().tolist()})"
                        )
    return r


def test_ep_layer3_dataset_consistency(num_problems: int = 3) -> TestResult:
    """Layer 3: The DATASET's own encode_sequence should match our reference encoder."""
    r = TestResult("8-puzzle Layer 3: dataset.encode_sequence matches reference")
    try:
        from data.eight_puzzle import EightPuzzleDataset
    except Exception as e:
        r.assert_(False, f"could not import EightPuzzleDataset: {e}")
        return r

    for seed in range(num_problems):
        for use_wm in [False, True]:
            ds = EightPuzzleDataset(difficulty_range=(5, 10), num_samples=1,
                                     use_world_model=use_wm, seed=seed)
            problem = ds.generate_problem(difficulty=5 + seed)
            their_seq = ds.encode_sequence(problem)
            our_seq = ep_encode_problem(problem, use_world_model=use_wm)
            r.assert_(
                their_seq == our_seq,
                f"seed={seed} wm={use_wm}: dataset encoder produces different sequence "
                f"than reference encoder.\n"
                f"      first 25 of dataset: {their_seq[:25]}\n"
                f"      first 25 of ours:    {our_seq[:25]}\n"
                f"      (if different at first state-block ~index 21, this is the "
                f"pre-move-vs-post-move bug)"
            )
    return r


def test_ep_layer4_cache_verification(cache_dir: str = 'cached_data') -> TestResult:
    """Layer 4: Verify cached 8-puzzle data is internally consistent."""
    r = TestResult("8-puzzle Layer 4: cached data internal consistency")
    cache_files = [
        (f'{cache_dir}/eight_puzzle_train_baseline.json', False),
        (f'{cache_dir}/eight_puzzle_test_baseline.json',  False),
        (f'{cache_dir}/eight_puzzle_train_wm.json',       True),
        (f'{cache_dir}/eight_puzzle_test_wm.json',        True),
    ]
    for path, use_wm in cache_files:
        if not Path(path).exists():
            print(f"      (skipping: {path} not present)")
            continue
        with open(path) as f:
            problems = json.load(f)
        print(f"      checking {path} ({len(problems)} problems, "
              f"WM={'yes' if use_wm else 'no'})")

        # Spot-check first 10 problems
        for i, p in enumerate(problems[:10]):
            seq = p['sequence']
            try:
                decoded = ep_decode_problem(seq, use_world_model=use_wm)
            except Exception as e:
                r.assert_(False, f"{path}[{i}]: decode failed: {e}")
                continue

            # The reference plan should reach the goal
            cur = decoded['start_state'].copy()
            for mv in decoded['solution_moves']:
                nxt = ep_apply_move(cur, mv)
                if nxt is None:
                    r.assert_(False, f"{path}[{i}]: invalid move '{mv}' in cached plan")
                    break
                cur = nxt
            else:
                r.assert_(
                    np.array_equal(cur, decoded['goal_state']),
                    f"{path}[{i}]: applying cached moves does NOT reach the goal. "
                    f"final={cur.flatten().tolist()}, goal={decoded['goal_state'].flatten().tolist()}"
                )

            # For WM: check whether state blocks are POST-move (current convention)
            # or PRE-move (the bug we found)
            if use_wm and len(decoded['solution_states']) > 0:
                cur = decoded['start_state'].copy()
                post_match = 0
                pre_match = 0
                for k, mv in enumerate(decoded['solution_moves']):
                    if k >= len(decoded['solution_states']):
                        break
                    nxt = ep_apply_move(cur, mv)
                    if nxt is None:
                        break
                    if np.array_equal(decoded['solution_states'][k], nxt):
                        post_match += 1
                    elif np.array_equal(decoded['solution_states'][k], cur):
                        pre_match += 1
                    cur = nxt
                n = len(decoded['solution_states'])
                if i == 0:  # print convention diagnosis for first problem only
                    if pre_match == n and post_match == 0:
                        print(f"        problem 0: ALL state blocks match PRE-move state "
                              f"(off-by-one bug confirmed)")
                    elif post_match == n and pre_match == 0:
                        print(f"        problem 0: ALL state blocks match POST-move state (correct)")
                    else:
                        print(f"        problem 0: mixed conventions "
                              f"(pre={pre_match}, post={post_match}, n={n})")
                # The check itself: all state blocks should match POST-move
                r.assert_(
                    post_match == n,
                    f"{path}[{i}]: state-block convention violation "
                    f"(pre-move matches: {pre_match}, post-move matches: {post_match}, n={n})"
                )
    return r


def test_bw_layer1_strict_roundtrip(num_problems: int = 3) -> TestResult:
    """Layer 1 (BW): strict, fully lossless round-trip.

    With the new uniform encoding the round-trip is now strict, not lossy.
    encode(state) then decode_state(...) should recover state byte-for-byte.
    """
    r = TestResult("BW Layer 1: strict round-trip (fresh problems)")
    try:
        from data.blocks_world import BlocksWorldDataset
    except Exception as e:
        r.assert_(False, f"could not import BlocksWorldDataset: {e}")
        return r

    for seed in range(num_problems):
        for use_wm in [False, True]:
            ds = BlocksWorldDataset(difficulty_range=(3, 5), num_samples=1,
                                     use_world_model=use_wm, seed=seed)
            problem = ds.generate_problem(difficulty=3 + seed)

            # Reference encode (our independent implementation), then decode
            seq = bw_encode_problem(problem, use_world_model=use_wm)
            decoded = bw_decode_problem(seq, use_world_model=use_wm)

            r.assert_(
                decoded['start_state'] == problem['start_state'],
                f"seed={seed} wm={use_wm}: start_state mismatch "
                f"(decoded={decoded['start_state']}, expected={problem['start_state']})"
            )
            r.assert_(
                decoded['goal_state'] == problem['goal_state'],
                f"seed={seed} wm={use_wm}: goal_state mismatch "
                f"(decoded={decoded['goal_state']}, expected={problem['goal_state']})"
            )
            r.assert_(
                decoded['solution_moves'] == problem['solution_moves'],
                f"seed={seed} wm={use_wm}: solution_moves mismatch: "
                f"decoded={decoded['solution_moves']} expected={problem['solution_moves']}"
            )
            r.assert_(
                decoded['num_moves'] == problem['num_moves'],
                f"seed={seed} wm={use_wm}: num_moves mismatch"
            )

            # Uniform-length check: each state block should be exactly 8 tokens.
            # We can verify by reconstructing: every state block is 8 tokens.
            if use_wm:
                # The encoder pairs move i with the POST-move state. Verify the
                # decoded intermediate states match what we get by applying moves.
                cur = [t[:] for t in problem['start_state']]
                for k, mv in enumerate(problem['solution_moves']):
                    cur = bw_apply_action(cur, mv)
                    if k < len(decoded['solution_states']):
                        r.assert_(
                            decoded['solution_states'][k] == cur,
                            f"seed={seed}: post-move state {k} mismatch "
                            f"(decoded={decoded['solution_states'][k]}, expected={cur})"
                        )
                # Number of state blocks should equal number of moves
                r.assert_(
                    len(decoded['solution_states']) == problem['num_moves'],
                    f"seed={seed}: expected {problem['num_moves']} state blocks, "
                    f"got {len(decoded['solution_states'])}"
                )
    return r


def test_bw_layer3_dataset_consistency(num_problems: int = 3) -> TestResult:
    """Layer 3 (BW): the dataset's encode_sequence must match our reference encoder."""
    r = TestResult("BW Layer 3: dataset.encode_sequence matches reference")
    try:
        from data.blocks_world import BlocksWorldDataset
    except Exception as e:
        r.assert_(False, f"could not import BlocksWorldDataset: {e}")
        return r

    for seed in range(num_problems):
        for use_wm in [False, True]:
            ds = BlocksWorldDataset(difficulty_range=(3, 5), num_samples=1,
                                     use_world_model=use_wm, seed=seed)
            problem = ds.generate_problem(difficulty=3 + seed)
            their_seq = ds.encode_sequence(problem)
            our_seq = bw_encode_problem(problem, use_world_model=use_wm)
            r.assert_(
                their_seq == our_seq,
                f"seed={seed} wm={use_wm}: dataset encoder differs from reference\n"
                f"      dataset (first 30): {their_seq[:30]}\n"
                f"      ours    (first 30): {our_seq[:30]}\n"
                f"      dataset total len:  {len(their_seq)}\n"
                f"      ours total len:     {len(our_seq)}"
            )
    return r


def test_bw_layer4_cache_verification(cache_dir: str = 'cached_data') -> TestResult:
    """Layer 4 (BW): cached data must decode losslessly and be internally consistent."""
    r = TestResult("BW Layer 4: cached data internal consistency")
    cache_files = [
        (f'{cache_dir}/blocks_world_train_baseline.json', False),
        (f'{cache_dir}/blocks_world_test_baseline.json',  False),
        (f'{cache_dir}/blocks_world_train_wm.json',       True),
        (f'{cache_dir}/blocks_world_test_wm.json',        True),
    ]
    for path, use_wm in cache_files:
        if not Path(path).exists():
            print(f"      (skipping: {path} not present)")
            continue
        with open(path) as f:
            problems = json.load(f)
        print(f"      checking {path} ({len(problems)} problems, "
              f"WM={'yes' if use_wm else 'no'})")

        for i, p in enumerate(problems[:10]):
            seq = p['sequence']
            try:
                decoded = bw_decode_problem(seq, use_world_model=use_wm)
            except Exception as e:
                r.assert_(False, f"{path}[{i}]: decode failed: {e}")
                continue

            # Recorded num_moves matches decoded
            if 'num_moves' in p:
                r.assert_(
                    decoded['num_moves'] == p['num_moves'],
                    f"{path}[{i}]: decoded {decoded['num_moves']} moves, "
                    f"problem reports {p['num_moves']}"
                )

            # The plan reaches the goal when applied to start (semantic check)
            cur = [t[:] for t in decoded['start_state']]
            ok_plan = True
            for k, mv in enumerate(decoded['solution_moves']):
                nxt = bw_apply_action(cur, mv)
                if nxt is None:
                    r.assert_(False, f"{path}[{i}]: invalid move {mv} at step {k}")
                    ok_plan = False
                    break
                cur = nxt
            if ok_plan:
                r.assert_(
                    cur == decoded['goal_state'],
                    f"{path}[{i}]: applying cached moves does NOT reach the goal "
                    f"(final={cur}, goal={decoded['goal_state']})"
                )

            # WM-only: every decoded intermediate state equals the post-move
            # state of the corresponding step (this is the post-move convention
            # we want -- a parallel to the 8-puzzle Layer 4 convention check)
            if use_wm:
                cur = [t[:] for t in decoded['start_state']]
                for k, mv in enumerate(decoded['solution_moves']):
                    if k >= len(decoded['solution_states']):
                        break
                    nxt = bw_apply_action(cur, mv)
                    if nxt is None:
                        break
                    r.assert_(
                        decoded['solution_states'][k] == nxt,
                        f"{path}[{i}] step {k}: state block does not match post-move state "
                        f"(decoded={decoded['solution_states'][k]}, expected={nxt})"
                    )
                    cur = nxt
    return r


# ============================================================================
# Main
# ============================================================================

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--domain', choices=['eight_puzzle', 'blocks_world', 'both'],
                    default='both')
    ap.add_argument('--num-fresh', type=int, default=3,
                    help='Number of freshly generated problems per (seed, wm) cell')
    ap.add_argument('--cache-dir', default='cached_data')
    ap.add_argument('--skip-cache', action='store_true',
                    help='Skip Layer 4 cache verification')
    args = ap.parse_args()

    print("=" * 76)
    print("ENCODING ROUND-TRIP TEST SUITE")
    print("=" * 76)

    results: List[TestResult] = []

    if args.domain in ('eight_puzzle', 'both'):
        print("\n--- 8-PUZZLE ---")
        results.append(test_ep_layer1_strict_roundtrip(args.num_fresh))
        results.append(test_ep_layer3_dataset_consistency(args.num_fresh))
        if not args.skip_cache:
            results.append(test_ep_layer4_cache_verification(args.cache_dir))

    if args.domain in ('blocks_world', 'both'):
        print("\n--- BLOCKS WORLD ---")
        results.append(test_bw_layer1_strict_roundtrip(args.num_fresh))
        results.append(test_bw_layer3_dataset_consistency(args.num_fresh))
        if not args.skip_cache:
            results.append(test_bw_layer4_cache_verification(args.cache_dir))

    print("\n" + "=" * 76)
    print("SUMMARY")
    print("=" * 76)
    total_passed = sum(r.passed for r in results)
    total_failed = sum(r.failed for r in results)
    for r in results:
        print(r.summary())
        for msg in r.failures[:10]:  # cap noise
            print(f"      - {msg}")
        if len(r.failures) > 10:
            print(f"      ... and {len(r.failures) - 10} more")
    print("-" * 76)
    print(f"TOTAL: {total_passed} passed, {total_failed} failed")
    print("=" * 76)

    sys.exit(0 if total_failed == 0 else 1)


if __name__ == '__main__':
    main()
