#!/usr/bin/env python3
"""
Regenerate the 8-puzzle WM cache files from scratch using the current
(post-fix) data/eight_puzzle.py.

Why
---
The existing cache was generated by a buggy version of encode_sequence that
paired each move with the PRE-move state. After applying the fix
(fix_eight_puzzle_encoding.py), the encoder pairs each move with the
POST-move state, so the model can be trained on data where the in-context
state-block actually corresponds to the state the model is supposed to
operate on. This script produces fresh cache files using the fixed encoder.

What this does
--------------
1. Backs up the existing cache files to cached_data/*.bak-<timestamp>
2. Generates fresh 8-puzzle WM train + test data using the same parameters
   as the standard (10, 15) setup that previous runs used:
       train: 5000 problems, difficulty in [10, 15]
       test:  500 problems,  difficulty in [10, 15]
3. Writes them to cached_data/eight_puzzle_train_wm.json and
   cached_data/eight_puzzle_test_wm.json (replacing the old files after
   backing them up).
4. Verifies the new cache by running the Layer 4 internal-consistency
   check from test_encoding_roundtrip on the first 10 problems.

Does NOT touch the baseline cache files -- those aren't affected by the
encoder bug (baseline doesn't emit state blocks).

Usage
-----
    python3 regen_eight_puzzle_wm_cache.py
    python3 regen_eight_puzzle_wm_cache.py --train-samples 5000 --test-samples 500
    python3 regen_eight_puzzle_wm_cache.py --seed 42
    python3 regen_eight_puzzle_wm_cache.py --dry-run  # generate but don't overwrite
"""

import argparse
import json
import shutil
import sys
import time
from pathlib import Path


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--difficulty-min", type=int, default=10)
    ap.add_argument("--difficulty-max", type=int, default=15)
    ap.add_argument("--train-samples", type=int, default=5000)
    ap.add_argument("--test-samples", type=int, default=500)
    ap.add_argument("--seed", type=int, default=42,
                    help="Seed for train; test uses seed+1")
    ap.add_argument("--cache-dir", default="cached_data")
    ap.add_argument("--dry-run", action="store_true",
                    help="Generate and verify, but don't overwrite the existing cache")
    args = ap.parse_args()

    cache_dir = Path(args.cache_dir)
    cache_dir.mkdir(exist_ok=True)
    train_path = cache_dir / "eight_puzzle_train_wm.json"
    test_path = cache_dir / "eight_puzzle_test_wm.json"

    # Import the dataset class (after the patch is applied)
    sys.path.insert(0, ".")
    try:
        from data.eight_puzzle import EightPuzzleDataset
    except ImportError as e:
        print(f"ERROR: could not import data.eight_puzzle: {e}")
        sys.exit(1)

    # Quick sanity check: confirm the encoder uses the post-move convention.
    # We do this before generating anything so we don't waste 30 minutes
    # producing a cache that's still buggy.
    print("Sanity check: inspecting the encoder source...")
    import inspect
    enc_src = inspect.getsource(EightPuzzleDataset.encode_sequence)
    if "solution_states'][i + 1]" in enc_src or 'solution_states"][i + 1]' in enc_src:
        print("  ✓ Encoder uses solution_states[i + 1] (post-move).")
    elif "solution_states'][i]" in enc_src or 'solution_states"][i]' in enc_src:
        print("  ✗ Encoder still uses solution_states[i] (pre-move; the bug).")
        print("    Run fix_eight_puzzle_encoding.py first, then re-run this script.")
        sys.exit(2)
    else:
        print("  ⚠️  Could not find the expected slicing pattern in the encoder source.")
        print("     The encoder may have been refactored; verify manually before proceeding.")
        print()
        print(enc_src)
        sys.exit(3)
    print()

    # Generate train set
    print(f"Generating {args.train_samples} train problems "
          f"with difficulty in [{args.difficulty_min}, {args.difficulty_max}]...")
    t0 = time.time()
    train_ds = EightPuzzleDataset(
        difficulty_range=(args.difficulty_min, args.difficulty_max),
        num_samples=args.train_samples,
        use_world_model=True,
        seed=args.seed,
    )
    train_data = train_ds.generate_dataset()
    print(f"  Done in {time.time() - t0:.1f}s -- {len(train_data)} problems.")

    # Generate test set
    print(f"Generating {args.test_samples} test problems...")
    t0 = time.time()
    test_ds = EightPuzzleDataset(
        difficulty_range=(args.difficulty_min, args.difficulty_max),
        num_samples=args.test_samples,
        use_world_model=True,
        seed=args.seed + 1,
    )
    test_data = test_ds.generate_dataset()
    print(f"  Done in {time.time() - t0:.1f}s -- {len(test_data)} problems.")

    # Verify each generated cache by running the Layer 4 consistency check
    # inline (we don't import test_encoding_roundtrip to keep this script
    # independent, but we replicate the check).
    print("Verifying internal consistency of the new cache...")
    failures = run_layer4_check(train_data, "train") + run_layer4_check(test_data, "test")
    if failures:
        print(f"  ✗ {len(failures)} consistency failures:")
        for f in failures[:5]:
            print(f"      - {f}")
        if len(failures) > 5:
            print(f"      ... and {len(failures) - 5} more")
        print("  Not overwriting the existing cache. Investigate before continuing.")
        sys.exit(4)
    print(f"  ✓ All checks passed.")
    print()

    if args.dry_run:
        print("Dry run; not overwriting existing cache files.")
        print(f"  Would have written: {train_path}")
        print(f"  Would have written: {test_path}")
        sys.exit(0)

    # Back up the existing cache
    timestamp = time.strftime("%Y%m%d-%H%M%S")
    for path in (train_path, test_path):
        if path.exists():
            backup = path.with_name(path.name + f".bak-{timestamp}")
            shutil.copy2(path, backup)
            print(f"Backed up {path} -> {backup}")

    # Write the new cache
    with open(train_path, "w") as f:
        json.dump(train_data, f)
    print(f"Wrote {train_path} ({len(train_data)} problems)")
    with open(test_path, "w") as f:
        json.dump(test_data, f)
    print(f"Wrote {test_path} ({len(test_data)} problems)")

    print()
    print("Next steps:")
    print("  1. Re-run the round-trip test to confirm Layer 4 now passes:")
    print("       python3 test_encoding_roundtrip.py --domain eight_puzzle")
    print("  2. Retrain medium WM 8-puzzle:")
    print("       python3 run_experiments.py --sweep model_size --domain eight_puzzle \\")
    print("           --sizes medium")
    print("  3. Compare the new solve rate against the previous (buggy) 5%.")


def run_layer4_check(problems, label):
    """Verify each problem decodes consistently:
    - state-block convention is post-move
    - applying the moves to the start reaches the goal
    Checks the first 10 problems and returns a list of failure descriptions.
    """
    import numpy as np

    failures = []
    EP_MOVE_TO_TOKEN = {'up': 10, 'down': 11, 'left': 12, 'right': 13}
    EP_TOKEN_TO_MOVE = {v: k for k, v in EP_MOVE_TO_TOKEN.items()}
    EP_SEP = 14
    EP_PAD = 15

    def apply_move(state, move):
        s = state.copy()
        pos = np.argwhere(s == 0)
        if len(pos) == 0:
            return None
        r, c = pos[0]
        if move == 'up' and r > 0:
            s[r, c], s[r-1, c] = s[r-1, c], s[r, c]
        elif move == 'down' and r < 2:
            s[r, c], s[r+1, c] = s[r+1, c], s[r, c]
        elif move == 'left' and c > 0:
            s[r, c], s[r, c-1] = s[r, c-1], s[r, c]
        elif move == 'right' and c < 2:
            s[r, c], s[r, c+1] = s[r, c+1], s[r, c]
        else:
            return None
        return s

    for i, p in enumerate(problems[:10]):
        seq = p['sequence']
        if seq[0] != 13 or seq[10] != EP_PAD or seq[-1] != EP_SEP:
            failures.append(f"{label}[{i}]: header/footer tokens wrong")
            continue
        start = np.array(seq[1:10]).reshape(3, 3)
        goal = np.array(seq[11:20]).reshape(3, 3)

        # Walk through moves + state blocks
        cur = start.copy()
        pos = 20
        step = 0
        while pos < len(seq) - 1:
            tok = seq[pos]
            if tok not in EP_TOKEN_TO_MOVE:
                failures.append(f"{label}[{i}] step {step}: bad move token {tok}")
                break
            mv = EP_TOKEN_TO_MOVE[tok]
            cur_after = apply_move(cur, mv)
            if cur_after is None:
                failures.append(f"{label}[{i}] step {step}: invalid move {mv}")
                break
            # Next 9 tokens should be the post-move state
            state_block = np.array(seq[pos+1:pos+10]).reshape(3, 3)
            if not np.array_equal(state_block, cur_after):
                failures.append(
                    f"{label}[{i}] step {step}: state block does not match post-move state "
                    f"(got {state_block.flatten().tolist()}, "
                    f"expected {cur_after.flatten().tolist()})"
                )
                break
            cur = cur_after
            pos += 10
            step += 1

        # After all moves, cur should equal goal
        if not np.array_equal(cur, goal):
            failures.append(
                f"{label}[{i}]: after applying all moves, did NOT reach goal "
                f"(final={cur.flatten().tolist()}, goal={goal.flatten().tolist()})"
            )

    return failures


if __name__ == "__main__":
    main()
