#!/usr/bin/env python3
"""
Regenerate the Blocks World cache files from scratch using the now-fixed
data/blocks_world.py (uniform 8-token state encoding).

WHY
---
The existing cache was generated by the lossy _encode_state that emitted only
the top block of each tower with POS_0 padding. After applying
fix_blocks_world_encoding.py, the encoder produces uniform 8-token state
blocks (top-to-bottom within each tower, separator always emitted). The old
cache is structurally incompatible with the new encoder and must be replaced.

This script:
1. Sanity-checks that the new encoder is actually in place (refuses to run
   otherwise, so we don't waste minutes producing a still-lossy cache).
2. Generates train and test data for both baseline and WM modes, using the
   same parameters as the standard setup.
3. Backs up the existing caches with a timestamp suffix and writes new files
   into their place.
4. Verifies the result with an inline Layer 4 internal-consistency check
   before overwriting.

DEFAULTS
--------
Match the standard (1, 6) difficulty range and 20000/2000 samples that
previous Blocks World experiments used. Override on the command line if
different.

USAGE
-----
    python3 regen_blocks_world_cache.py                # do it
    python3 regen_blocks_world_cache.py --dry-run      # generate and verify only
    python3 regen_blocks_world_cache.py --train-samples 20000 --test-samples 2000
    python3 regen_blocks_world_cache.py --baseline-only        # skip WM cache
    python3 regen_blocks_world_cache.py --wm-only              # skip baseline cache
"""

import argparse
import json
import shutil
import sys
import time
from pathlib import Path


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--difficulty-min", type=int, default=1)
    ap.add_argument("--difficulty-max", type=int, default=6)
    ap.add_argument("--train-samples", type=int, default=20000)
    ap.add_argument("--test-samples", type=int, default=2000)
    ap.add_argument("--seed", type=int, default=42,
                    help="Train uses seed; test uses seed+1; WM and baseline use distinct seeds")
    ap.add_argument("--cache-dir", default="cached_data")
    ap.add_argument("--dry-run", action="store_true")
    ap.add_argument("--baseline-only", action="store_true")
    ap.add_argument("--wm-only", action="store_true")
    args = ap.parse_args()

    cache_dir = Path(args.cache_dir)
    cache_dir.mkdir(exist_ok=True)

    sys.path.insert(0, ".")
    try:
        from data.blocks_world import BlocksWorldDataset
    except ImportError as e:
        print(f"ERROR: could not import data.blocks_world: {e}")
        sys.exit(1)

    # --- Sanity check the encoder ---
    print("Sanity check: verifying the new uniform encoder is in place...")
    ds_probe = BlocksWorldDataset(difficulty_range=(3, 3), num_samples=1,
                                   use_world_model=False, seed=0)
    if not hasattr(ds_probe, '_decode_state'):
        print("  ✗ BlocksWorldDataset has no _decode_state method.")
        print("    The fix has not been applied. Run fix_blocks_world_encoding.py first.")
        sys.exit(2)
    test_state = [['A', 'B', 'C'], [], ['D'], []]
    enc = ds_probe._encode_state(test_state)
    if len(enc) != 8:
        print(f"  ✗ _encode_state produced {len(enc)} tokens for a test state; expected 8.")
        print("    The encoder is not the uniform 8-token version. Patch may be incomplete.")
        sys.exit(3)
    if ds_probe._decode_state(enc) != test_state:
        print("  ✗ encoder/decoder do not round-trip.")
        sys.exit(4)
    print(f"  ✓ encoder produces 8 tokens for {test_state}: {enc}")
    print(f"  ✓ round-trip decodes back to the original state.")
    print()

    # --- What to regenerate ---
    todo = []
    if not args.wm_only:
        todo.append(('baseline', False))
    if not args.baseline_only:
        todo.append(('wm', True))

    new_caches = {}  # (label, split) -> list of problems
    for label, use_wm in todo:
        for split, n_samples, seed_off in [
            ('train', args.train_samples, 0),
            ('test',  args.test_samples,  1),
        ]:
            seed = args.seed + (100 if use_wm else 0) + seed_off
            print(f"Generating {n_samples} {label} {split} problems "
                  f"(difficulty {args.difficulty_min}-{args.difficulty_max}, seed={seed})...")
            t0 = time.time()
            ds = BlocksWorldDataset(
                difficulty_range=(args.difficulty_min, args.difficulty_max),
                num_samples=n_samples,
                use_world_model=use_wm,
                seed=seed,
            )
            data = ds.generate_dataset()
            print(f"  Done in {time.time() - t0:.1f}s -- {len(data)} problems.")
            new_caches[(label, split)] = data

    # --- Verify each generated cache ---
    print()
    print("Verifying internal consistency of the new caches...")
    for (label, split), data in new_caches.items():
        use_wm = (label == 'wm')
        failures = run_layer4_check(data, use_wm, label_str=f"{label}/{split}")
        if failures:
            print(f"  ✗ {label}/{split}: {len(failures)} failures:")
            for f in failures[:5]:
                print(f"      - {f}")
            if len(failures) > 5:
                print(f"      ... and {len(failures) - 5} more")
            print("  Not overwriting the existing cache. Investigate before continuing.")
            sys.exit(5)
        else:
            print(f"  ✓ {label}/{split}: OK")
    print()

    if args.dry_run:
        print("Dry run; not overwriting existing cache files.")
        for (label, split), data in new_caches.items():
            print(f"  Would have written: {target_path(cache_dir, label, split)} "
                  f"({len(data)} problems)")
        sys.exit(0)

    # --- Back up and write ---
    timestamp = time.strftime("%Y%m%d-%H%M%S")
    for (label, split), data in new_caches.items():
        path = target_path(cache_dir, label, split)
        if path.exists():
            backup = path.with_name(path.name + f".bak-{timestamp}")
            shutil.copy2(path, backup)
            print(f"Backed up {path} -> {backup}")
        with open(path, "w") as f:
            json.dump(data, f)
        print(f"Wrote {path} ({len(data)} problems)")

    print()
    print("Next steps:")
    print("  1. Re-run the round-trip test to confirm Layer 4 now passes:")
    print("       python3 test_encoding_roundtrip.py --domain blocks_world")
    print("  2. Update downstream tooling for the new 8-token state stride:")
    print("     calibrate_sep.py (action_len=2, state_len=8, context_end=17)")
    print("     trace_one_problem.py (same)")
    print("  3. Retrain at least medium WM + medium baseline:")
    print("       python3 run_experiments.py --sweep model_size --domain blocks_world \\")
    print("           --sizes medium")
    print("     Compare new solve rates against previous numbers (was: WM=75%, base=8%).")


def target_path(cache_dir, label, split):
    """e.g. cached_data/blocks_world_train_wm.json"""
    return cache_dir / f"blocks_world_{split}_{label}.json"


def run_layer4_check(problems, use_wm, label_str=""):
    """Decode the first 10 problems and verify:
      - applying the cached moves to the cached start reaches the cached goal
      - in WM mode, each state-block matches the post-move state
    Returns a list of failure messages.
    """
    # Local mirrors of the BW constants and decoder, to keep this script
    # independent of test_encoding_roundtrip.py.
    BW_VOCAB = {
        'START': 0, 'END': 1,
        'A': 2, 'B': 3, 'C': 4, 'D': 5,
        'POS_0': 6, 'POS_1': 7, 'POS_2': 8, 'POS_3': 9,
        'PAD': 10,
    }
    BW_INV = {v: k for k, v in BW_VOCAB.items()}
    BW_BLOCKS = ['A', 'B', 'C', 'D']
    BW_NUM_POSITIONS = 4
    BW_STATE_LEN = 8
    BW_ACTION_LEN = 2
    BW_CONTEXT_END = 1 + BW_STATE_LEN + BW_STATE_LEN
    BW_POS_TOKENS = {BW_VOCAB[f'POS_{k}']: k for k in range(BW_NUM_POSITIONS)}
    BW_BLOCK_TOKENS = {BW_VOCAB[b] for b in BW_BLOCKS}

    def decode_state(tokens):
        if len(tokens) != BW_STATE_LEN:
            raise ValueError(f"expected {BW_STATE_LEN}-token state, got {len(tokens)}")
        state = [[] for _ in range(BW_NUM_POSITIONS)]
        buf = []
        for tok in tokens:
            if tok in BW_BLOCK_TOKENS:
                buf.append(BW_INV[tok])
            elif tok in BW_POS_TOKENS:
                state[BW_POS_TOKENS[tok]] = list(reversed(buf))
                buf = []
            else:
                raise ValueError(f"unexpected token {tok}")
        if buf:
            raise ValueError(f"trailing tokens: {buf}")
        return state

    def apply_action(state, action):
        block, dest_pos = action
        src = None
        for k, t in enumerate(state):
            if t and t[-1] == block:
                src = k
                break
        if src is None:
            return None
        new_state = [t[:] for t in state]
        new_state[src].pop()
        new_state[dest_pos].append(block)
        return new_state

    failures = []
    for i, p in enumerate(problems[:10]):
        seq = p['sequence']
        if seq[0] != BW_VOCAB['START'] or seq[-1] != BW_VOCAB['END']:
            failures.append(f"{label_str}[{i}]: header/footer wrong")
            continue
        try:
            start_state = decode_state(seq[1:1 + BW_STATE_LEN])
            goal_state = decode_state(seq[1 + BW_STATE_LEN:BW_CONTEXT_END])
        except Exception as e:
            failures.append(f"{label_str}[{i}]: decode start/goal failed: {e}")
            continue

        cur = [t[:] for t in start_state]
        pos = BW_CONTEXT_END
        step = 0
        plan_ok = True
        while pos < len(seq) - 1:
            block_tok, pos_tok = seq[pos], seq[pos + 1]
            if block_tok not in BW_BLOCK_TOKENS or pos_tok not in BW_POS_TOKENS:
                failures.append(f"{label_str}[{i}] step {step}: bad action tokens "
                                f"{block_tok},{pos_tok}")
                plan_ok = False
                break
            move = [BW_INV[block_tok], BW_POS_TOKENS[pos_tok]]
            nxt = apply_action(cur, move)
            if nxt is None:
                failures.append(f"{label_str}[{i}] step {step}: invalid move {move}")
                plan_ok = False
                break
            pos += BW_ACTION_LEN

            if use_wm:
                if pos + BW_STATE_LEN > len(seq):
                    failures.append(
                        f"{label_str}[{i}] step {step}: ran out of tokens for state block"
                    )
                    plan_ok = False
                    break
                try:
                    state_block_decoded = decode_state(seq[pos:pos + BW_STATE_LEN])
                except Exception as e:
                    failures.append(f"{label_str}[{i}] step {step}: decode state failed: {e}")
                    plan_ok = False
                    break
                if state_block_decoded != nxt:
                    failures.append(
                        f"{label_str}[{i}] step {step}: state block != post-move state "
                        f"(got {state_block_decoded}, expected {nxt})"
                    )
                    plan_ok = False
                    break
                pos += BW_STATE_LEN
            cur = nxt
            step += 1

        if plan_ok and cur != goal_state:
            failures.append(
                f"{label_str}[{i}]: after applying all moves, did NOT reach goal "
                f"(final={cur}, goal={goal_state})"
            )
    return failures


if __name__ == "__main__":
    main()
